### PR TITLE
Fix build on s390x arch

### PR DESCRIPTION
**Pull request by andypost**
just a typo

### CODE REVIEW

**Comment by rosmanov** [comment]
Thank you!

**Comment by andypost** [comment]
Thank you! Meantime used to package it for Alpinelinux and found the test `tests/eio_write_variation.phpt` not stable, for example https://gitlab.alpinelinux.org/alpine/aports/-/jobs/493575

**Comment by rosmanov** [comment]
> Meantime used to package it for Alpinelinux and found the test tests/eio_write_variation.phpt not stable, for example https://gitlab.alpinelinux.org/alpine/aports/-/jobs/493575

Hmm, I could try to reproduce it if I had some Dockerfile. But the problematic test was `tests/fork.phpt` (not `tests/eio_write_variation.phpt`), right?

```
TEST 29/29 [tests/fork.phpt]
========DIFF========
     w: 20 l: 20 f: 20 c: 20
002+ 
002- w: 20 l: 20 f: 20 c: 20
003+ Warning: eio_write(): Invalid file descriptor in /builds/alpine/aports/testing/php81-pecl-eio/src/eio-3.0.0RC4/tests/fork.php on line 21
004+ 
005+ Fatal error: Uncaught Exception: Invalid file descriptor in /builds/alpine/aports/testing/php81-pecl-eio/src/eio-3.0.0RC4/tests/fork.php:21
006+ Stack trace:
007+ #0 /builds/alpine/aports/testing/php81-pecl-eio/src/eio-3.0.0RC4/tests/fork.php(21): eio_write(-1, '111111111111111...', 20, 0, 0, Object(Closure), -1)
008+ #1 [internal function]: {closure}('/tmp/tmp_file61...', -1, Resource id #6)
009+ #2 /builds/alpine/aports/testing/php81-pecl-eio/src/eio-3.0.0RC4/tests/fork.php(23): eio_event_loop()
010+ #3 {main}
011+   thrown in /builds/alpine/aports/testing/php81-pecl-eio/src/eio-3.0.0RC4/tests/fork.php on line 21
========DONE========
FAIL Check for eio fork support using pcntl [tests/fork.phpt] 
```

**Comment by andypost** [comment]
Yes, each time the error a bit different

**Pull request merged**
